name: Deploy Demo
description: Build and deploy a charm to the Canonical web team demo service.
inputs:
  demo-id:
    required: true
    description: The unique ID for this demo.
  charm-root:
    required: false
    description: A path to the directory containing the charm.
    default: ./
  charm-path:
    required: false
    description: A path to a charm file.

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
    - name: Setup LXD
      uses: canonical/setup-lxd@main
    - name: Setup rockcraft
      shell: bash
      run: sudo snap install rockcraft --classic
    
    # Cache rock build
    - name: Cache rock
      id: cache-rock
      uses: actions/cache@v4
      with:
        path: "*.rock"
        key: rock-${{ hashFiles('rockcraft.yaml', 'app.py', 'requirements.txt') }}
    
    - name: Pack rock
      if: steps.cache-rock.outputs.cache-hit != 'true'
      shell: bash
      run: rockcraft pack
    
    - name: Set image URL
      id: set_image_url
      shell: bash
      run: |
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "image_url=ghcr.io/${REPO_LOWER}:${{ inputs.demo-id }}" >> $GITHUB_OUTPUT
    - name: Log in to GHCR
      shell: bash
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push rock to GHCR
      shell: bash
      run: |
        ROCK_FILE=$(ls *.rock)
        skopeo --insecure-policy copy oci-archive:$ROCK_FILE docker://${{ steps.set_image_url.outputs.image_url }} --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
    
    - name: Setup charmcraft
      shell: bash
      run: sudo snap install charmcraft --classic --channel=latest/stable
    
    # Cache charm build
    - name: Cache charm
      id: cache-charm
      uses: actions/cache@v4
      with:
        path: "${{ inputs.charm-root }}/*.charm"
        key: charm-${{ hashFiles(format('{0}/**', inputs.charm-root)) }}
    
    - name: Package charm with Charmcraft
      if: ${{ inputs.charm-path == '' && steps.cache-charm.outputs.cache-hit != 'true' }}
      id: pack
      shell: bash
      run: |
        cd ${{ inputs.charm-root }}
        charmcraft pack -v
        CHARM_FILE=$(ls *.charm)
        echo "charm_file=${CHARM_FILE}" >> $GITHUB_OUTPUT
    
    - name: Get charm name from cache
      if: ${{ inputs.charm-path == '' && steps.cache-charm.outputs.cache-hit == 'true' }}
      id: pack-cached
      shell: bash
      run: |
        cd ${{ inputs.charm-root }}
        CHARM_FILE=$(ls *.charm)
        echo "charm_file=${CHARM_FILE}" >> $GITHUB_OUTPUT
    
    - name: Get charm name
      if: ${{ inputs.charm-path == '' }}
      id: charm
      shell: bash
      run: |
        CHARM_FILE="${{ steps.pack.outputs.charm_file || steps.pack-cached.outputs.charm_file }}"
        echo "name=${{ inputs.charm-root }}/${CHARM_FILE}" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v6
      if: ${{ inputs.charm-path != '' || steps.charm.outputs.name != '' }}
      with:
        name: ${{ inputs.demo-id }}
        path: ${{ inputs.charm-path || steps.charm.outputs.name }}
        retention-days: 1
    - name: Install Juju
      shell: bash
      run: |
        sudo snap install juju
    - name: Authenticate with JAAS
      shell: bash
      env:
        JUJU_CLIENT_ID: ${{ secrets.DEMOS_JUJU_CLIENT_ID }}
        JUJU_CLIENT_SECRET: ${{ secrets.DEMOS_JUJU_CLIENT_SECRET }}
      run: |
        juju login jaas.ps7.canonical.com:443/k8s-jaas-ps7-jimm-jimm -c jaas-ps7
    - name: Deploy charm
      shell: bash
      env:
        JUJU_CLIENT_ID: ${{ secrets.DEMOS_JUJU_CLIENT_ID }}
        JUJU_CLIENT_SECRET: ${{ secrets.DEMOS_JUJU_CLIENT_SECRET }}
      run: |
        CHARM_FILE="${{ inputs.charm-path || steps.charm.outputs.name }}"
        juju deploy "$CHARM_FILE" ${{ inputs.demo-id }} \
          --resource flask-app-image=${{ steps.set_image_url.outputs.image_url }} \
          -m 795798e4-922f-49c7-9169-004ffc17df90@serviceaccount/k8s-webteam-demos-default
    - uses: ./.github/actions/demo-comment
      with:
        demo-id: ${{ inputs.demo-id }}
