name: Demo Comment
description: Create a comment on a PR for the demo service.
inputs:
  demo-id:
    required: true
    description: The unique ID for this demo.

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        DEMO_ID: ${{ inputs.demo-id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const demoServiceComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('<!-- demo_service -->')
          })
          if (demoServiceComment) {
            return;
          }
          // TODO: the URL needs to be updated to point at the real demo service.
          const output = `<!-- demo_service -->
          ### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://${{ process.env.DEMO_ID }}.example.com)`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
