name: Demo Commands
description: Control the demo with commands in PR comments.
inputs:
  enabled:
    required: false
    description: Whether the demo is currently enabled.
    default: true
  charm-root:
    required: false
    description: A path to the directory containing the charm.
    default: ./
  charm-path:
    required: false
    description: A path to a charm file.

runs:
  using: composite
  steps:
    - name: Start Demo
      if: contains(github.event.comment.body, '/start-demo') && inputs.enabled == 'false'
      uses: ./.github/actions/deploy-demo
      with:
        charm-root: ${{ inputs.charm-root }}
        charm-path: ${{ inputs.charm-path }}
    - name: Stop Demo
      if: contains(github.event.comment.body, '/stop-demo') && inputs.enabled == 'true'
      uses: ./.github/actions/cleanup-demo
    - name: Create Comment
      uses: ./.github/actions/demo-comment
      if: contains(github.event.comment.body, '/start-demo') || contains(github.event.comment.body, '/stop-demo')
    - name: Set Comment Status
      uses: actions/github-script@v7
      if: contains(github.event.comment.body, '/start-demo') || contains(github.event.comment.body, '/stop-demo')
      env:
        ENABLED: contains(github.event.comment.body, '/start-demo')
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const demoServiceComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('<!-- demo_service -->')
          })
          if (!demoServiceComment) {
            return;
          }
          const output = comment.body.replace(/Status: (\w+)/, `Status: ${process.env.ENABLED === "true" ? "enabled" : "disabled"}`);
          github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: botComment.id,
            body: output
          });
