name: Canonical Demo Service
description: Deploy a charm to the Canonical web team demo service.
inputs:
  charm-root:
    required: false
    description: A path to the directory containing the charm.
    default: ./
  charm-path:
    required: false
    description: A path to a charm file.

runs:
  using: composite
  steps:
    - name: Get demo ID
      id: demo-id
      shell: bash
      run: |
        echo "id=${{ github.event.repository.name }}-${{ github.event.pull_request.number || github.event.issue.number}}" >> $GITHUB_OUTPUT
    - uses: actions/github-script@v7
      id: enabled
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const demoServiceComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('<!-- demo_service -->')
          })
          return !demoServiceComment || demoServiceComment.body.includes('Status: enabled');
    - name: Publish Demo
      if: steps.enabled.outputs.result == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged != true && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
      uses: ./.github/actions/deploy-demo
      with:
        charm-root: ${{ inputs.charm-root }}
        charm-path: ${{ inputs.charm-path }}
        demo-id: ${{ inputs.demo-id }}
    - name: Clean Up Demo
      if: steps.enabled.outputs.result == 'true' && github.event_name == 'pull_request' && github.event.action == 'closed'
      uses: ./.github/actions/cleanup-demo
      with:
        demo-id: ${{ steps.demo-id.outputs.id }}
    - name: Handle Commands
      if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.action == 'created'
      uses: ./.github/actions/demo-commands
      with:
        enabled: ${{ steps.enabled.outputs.result }}
        charm-root: ${{ inputs.charm-root }}
        charm-path: ${{ inputs.charm-path }}
        demo-id: ${{ steps.demo-id.outputs.id }}
