name: Canonical Demo Service
description: Deploy a charm to the Canonical web team demo service.
inputs:
  charm-root:
    required: false
    description: A path to the directory containing the charm.
    default: ./
  charm-path:
    required: false
    description: A path to a charm file.

runs:
  using: composite
  steps:
    - name: Publish Demo
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
      uses: ./.github/actions/deploy-demo
      with:
        charm-root: ${{ inputs.charm-root }}
        charm-path: ${{ inputs.charm-path }}
    - name: Clean up Demo
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
      uses: ./.github/actions/cleanup-demo
